### PR TITLE
Create release only on push of tag

### PR DESCRIPTION
**Pull request by nadeemyaseen-rs**
With this update,
CI will trigger only on PR or on pushing a new tag
the release will be updated/created only on pushing a new tag

### CODE REVIEW

**Comment by guanyung-rs** [comment]
@nadeemyaseen-rs Just want to be sure when this PR get into main, the openocd cmake in FOEDAG is still pointing to the download path `set(download_path "https://github.com/RapidSilicon/openocd/releases/download/latest/${rs_openocd_tar}")` still able to work right? If yes, I think this PR is good to merge in.

**Review by guanyung-rs — APPROVED** [review]
@nadeemyaseen-rs Just want to be sure when this PR get into main, the openocd cmake in FOEDAG is still pointing to the download path set(download_path "https://github.com/RapidSilicon/openocd/releases/download/latest/${rs_openocd_tar}") still able to work right? If yes, I think this PR is good to merge in.

**Comment by nadeemyaseen-rs** [comment]
> @nadeemyaseen-rs Just want to be sure when this PR get into main, the openocd cmake in FOEDAG is still pointing to the download path set(download_path "[https://github.com/RapidSilicon/openocd/releases/download/latest/${rs_openocd_tar}](https://github.com/RapidSilicon/openocd/releases/download/latest/$%7Brs_openocd_tar%7D)") still able to work right? If yes, I think this PR is good to merge in.

Yes, if you push the tag only and let the workflow create the release.

**Comment by nadeemyaseen-rs** [comment]
@guanyung-rs kindly spare 10 to 20 minutes so that we can test this workflow.

**Comment by guanyung-rs** [comment]
I will test the workflow to make sure it works per plan

**Pull request merged**
